services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/.venv
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"